name: Build and Deploy

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Specify Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json" # Cache node_modules

      - name: Install dependencies (Client)
        working-directory: ./client # Navigate to client directory
        run: npm ci

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Install dependencies (API)
        working-directory: ./api # Navigate to api directory
        run: npm ci

      - name: Build API (If applicable - e.g., TypeScript)
        working-directory: ./api
        run: npm run build # Or tsc if using TypeScript

      - name: Upload Client Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-artifacts
          path: client/dist

      - name: Upload API Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-artifacts
          path: api/dist

      - name: Download Client Artifacts
        uses: actions/download-artifact@v3
        with:
          name: client-artifacts
          path: client/dist

      - name: Download API Artifacts
        uses: actions/download-artifact@v3
        with:
          name: api-artifacts
          path: api/dist

      - name: Deploy Client to Vercel
        if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
        run: npx vercel --prod -t ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy API to Vercel
        if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
        run: npx vercel --prod -t ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --prod
